### ISSUE TITLE
REST API for downloading gene information

### ISSUE THREAD

**Issue by pylipp** [DBKERO/genome_browser#1]
I was wondering whether it is possible to interact with the database in a REST-like fashion? I would like to get the genomic position info for, say the gene`RBL2`. Is it possible to construct a URL to obtain the corresponding `chr16:53,434,439-53,491,648:+`?

If this is not possible, where can I obtain the raw data that the database is built on? Is it http://kero.hgc.jp/data/hg38/data.dat? Or ftp://ftp.hgc.jp/pub/hgc/db/dbtss/vcf.tgz?

Thanks in advance.

**Comment by DBKERO** [comment]
In fact, as in-house web interface, we have interactive json URL. 
However, it can get gene information from genomic position but not genomic position from gene name.
 
For chr1, [http://kero.hgc.jp/cgi-bin/dbtss_db_json.cgi/9606/5/chr1/0/refGene/?SEE=1&UID=2](http://kero.hgc.jp/cgi-bin/dbtss_db_json.cgi/9606/5/chr1/0/refGene/?SEE=1&UID=2)
For chr2, http://kero.hgc.jp/cgi-bin/dbtss_db_json.cgi/9606/5/chr2/0/refGene/?SEE=1&UID=2
...
For chrX, http://kero.hgc.jp/cgi-bin/dbtss_db_json.cgi/9606/5/chrX/0/refGene/?SEE=1&UID=2

Here, /5/ is reduction level and /0/ is for positioning number.
http://kero.hgc.jp/cgi-bin/dbtss_db_json.cgi/9606/0/chr1/0/refGene/?SEE=1&UID=2 is chr1:1-10,000
http://kero.hgc.jp/cgi-bin/dbtss_db_json.cgi/9606/0/chr1/1/refGene/?SEE=1&UID=2 is chr1:10,001-20,000
...
http://kero.hgc.jp/cgi-bin/dbtss_db_json.cgi/9606/0/chr1/N/refGene/?SEE=1&UID=2 is chr1:(10,000 * N + 1) - (10,000 * (N + 1))

http://kero.hgc.jp/cgi-bin/dbtss_db_json.cgi/9606/1/chr1/1/refGene/?SEE=1&UID=2 is chr1:100,001-200,000
...
http://kero.hgc.jp/cgi-bin/dbtss_db_json.cgi/9606/M/chr1/N/refGene/?SEE=1&UID=2 is chr1:(10,000 * 10^M * N + 1) - (10,000 * 10^M * (N + 1))

But the version program uploaded to github don't include the json parser.

/////

If you simply need all of gene name and positions information on genome, 
please use BigBed file (http://kero.hgc.jp/data/hg38/genes.sorted.bb).
Thease original data can also dowonload from UCSC table browser.
(https://genome.ucsc.edu/cgi-bin/hgTables?clade=mammal&org=Human&db=hg38&hgta_group=genes&hgta_track=refSeqComposite&hgta_table=0&hgta_regionType=genome)

Thank you

**Comment by pylipp** [comment]
Thanks for the valuable information. The BigBed file contains exactly what I need. The `chromStart` field contains the TSS, right?

**Comment by DBKERO** [comment]
You need  `chromStart` field for plus (+) strand and `chromEnd` for minus (-) strand as TSS.
Note that `chromStart`  (of bed file) is the first base of the chromosome is numbered 0, while `chromEnd` is numbered 1.
(See https://genome.ucsc.edu/FAQ/FAQformat.html)

**Comment by pylipp** [comment]
Very helpful again, thank you.
